language: node_js
node_js:
  - "5.0.0"
  - "4.3.1"
  - "4.1"
  - "4.0"
script:
  - npm run build
addons:
  apt:
    pacakges:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
notifications:
  slack: flounder:CxUpXbQ1rlErXZR5xEqvNy2b